// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: access/access.proto

package protoAccess

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RPC通用请求消息
type RPCRequest struct {
	RemoteIP             string   `protobuf:"bytes,1,opt,name=RemoteIP" json:"RemoteIP"`
	RemotePort           int32    `protobuf:"varint,2,opt,name=RemotePort" json:"RemotePort"`
	AccSrvID             int32    `protobuf:"varint,3,opt,name=AccSrvID" json:"AccSrvID"`
	Seq                  int32    `protobuf:"varint,4,opt,name=Seq" json:"Seq"`
	UID                  int32    `protobuf:"varint,5,opt,name=UID" json:"UID"`
	Payload              []byte   `protobuf:"bytes,6,opt,name=Payload" json:"Payload"`
	ServerName           string   `protobuf:"bytes,7,opt,name=ServerName" json:"ServerName"`
	FuncName             string   `protobuf:"bytes,8,opt,name=FuncName" json:"FuncName"`
	RefererServerID      int32    `protobuf:"varint,9,opt,name=RefererServerID" json:"RefererServerID"`
	RefererServer        string   `protobuf:"bytes,10,opt,name=RefererServer" json:"RefererServer"`
	ExtData              string   `protobuf:"bytes,11,opt,name=ExtData" json:"ExtData"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCRequest) Reset()         { *m = RPCRequest{} }
func (m *RPCRequest) String() string { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()    {}
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_901fdf95822f51d8, []int{0}
}
func (m *RPCRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RPCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RPCRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RPCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRequest.Merge(m, src)
}
func (m *RPCRequest) XXX_Size() int {
	return m.Size()
}
func (m *RPCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRequest proto.InternalMessageInfo

func (m *RPCRequest) GetRemoteIP() string {
	if m != nil {
		return m.RemoteIP
	}
	return ""
}

func (m *RPCRequest) GetRemotePort() int32 {
	if m != nil {
		return m.RemotePort
	}
	return 0
}

func (m *RPCRequest) GetAccSrvID() int32 {
	if m != nil {
		return m.AccSrvID
	}
	return 0
}

func (m *RPCRequest) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *RPCRequest) GetUID() int32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *RPCRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RPCRequest) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *RPCRequest) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *RPCRequest) GetRefererServerID() int32 {
	if m != nil {
		return m.RefererServerID
	}
	return 0
}

func (m *RPCRequest) GetRefererServer() string {
	if m != nil {
		return m.RefererServer
	}
	return ""
}

func (m *RPCRequest) GetExtData() string {
	if m != nil {
		return m.ExtData
	}
	return ""
}

// RPC通用响应消息
type RPCResponse struct {
	Response             bool     `protobuf:"varint,1,opt,name=Response" json:"Response"`
	SrvName              string   `protobuf:"bytes,2,opt,name=SrvName" json:"SrvName"`
	SrvID                int32    `protobuf:"varint,3,opt,name=SrvID" json:"SrvID"`
	UID                  int32    `protobuf:"varint,4,opt,name=UID" json:"UID"`
	Seq                  int32    `protobuf:"varint,5,opt,name=Seq" json:"Seq"`
	Code                 int32    `protobuf:"varint,6,opt,name=Code" json:"Code"`
	Cmd                  int32    `protobuf:"varint,7,opt,name=Cmd" json:"Cmd"`
	Payload              []byte   `protobuf:"bytes,8,opt,name=Payload" json:"Payload"`
	Token                string   `protobuf:"bytes,9,opt,name=Token" json:"Token"`
	SetCookie            bool     `protobuf:"varint,10,opt,name=SetCookie" json:"SetCookie"`
	Disconnect           bool     `protobuf:"varint,12,opt,name=Disconnect" json:"Disconnect"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCResponse) Reset()         { *m = RPCResponse{} }
func (m *RPCResponse) String() string { return proto.CompactTextString(m) }
func (*RPCResponse) ProtoMessage()    {}
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_901fdf95822f51d8, []int{1}
}
func (m *RPCResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RPCResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RPCResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RPCResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCResponse.Merge(m, src)
}
func (m *RPCResponse) XXX_Size() int {
	return m.Size()
}
func (m *RPCResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RPCResponse proto.InternalMessageInfo

func (m *RPCResponse) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

func (m *RPCResponse) GetSrvName() string {
	if m != nil {
		return m.SrvName
	}
	return ""
}

func (m *RPCResponse) GetSrvID() int32 {
	if m != nil {
		return m.SrvID
	}
	return 0
}

func (m *RPCResponse) GetUID() int32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *RPCResponse) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *RPCResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RPCResponse) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *RPCResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RPCResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RPCResponse) GetSetCookie() bool {
	if m != nil {
		return m.SetCookie
	}
	return false
}

func (m *RPCResponse) GetDisconnect() bool {
	if m != nil {
		return m.Disconnect
	}
	return false
}

// 设置登录状态请求消息
type SetUIDReq struct {
	UID                  int32    `protobuf:"varint,1,opt,name=UID" json:"UID"`
	RemoteIP             string   `protobuf:"bytes,2,opt,name=RemoteIP" json:"RemoteIP"`
	RemotePort           int32    `protobuf:"varint,3,opt,name=RemotePort" json:"RemotePort"`
	ExtData              string   `protobuf:"bytes,4,opt,name=ExtData" json:"ExtData"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUIDReq) Reset()         { *m = SetUIDReq{} }
func (m *SetUIDReq) String() string { return proto.CompactTextString(m) }
func (*SetUIDReq) ProtoMessage()    {}
func (*SetUIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_901fdf95822f51d8, []int{2}
}
func (m *SetUIDReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetUIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetUIDReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetUIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUIDReq.Merge(m, src)
}
func (m *SetUIDReq) XXX_Size() int {
	return m.Size()
}
func (m *SetUIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetUIDReq proto.InternalMessageInfo

func (m *SetUIDReq) GetUID() int32 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *SetUIDReq) GetRemoteIP() string {
	if m != nil {
		return m.RemoteIP
	}
	return ""
}

func (m *SetUIDReq) GetRemotePort() int32 {
	if m != nil {
		return m.RemotePort
	}
	return 0
}

func (m *SetUIDReq) GetExtData() string {
	if m != nil {
		return m.ExtData
	}
	return ""
}

// 设置登录状态响应消息
type SetUIDRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code" json:"Code"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg" json:"Msg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUIDRsp) Reset()         { *m = SetUIDRsp{} }
func (m *SetUIDRsp) String() string { return proto.CompactTextString(m) }
func (*SetUIDRsp) ProtoMessage()    {}
func (*SetUIDRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_901fdf95822f51d8, []int{3}
}
func (m *SetUIDRsp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetUIDRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SetUIDRsp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SetUIDRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUIDRsp.Merge(m, src)
}
func (m *SetUIDRsp) XXX_Size() int {
	return m.Size()
}
func (m *SetUIDRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUIDRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SetUIDRsp proto.InternalMessageInfo

func (m *SetUIDRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SetUIDRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 发送回客户端请求
type OperationReq struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid" json:"uid"`
	Info                 []byte   `protobuf:"bytes,2,opt,name=info" json:"info"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationReq) Reset()         { *m = OperationReq{} }
func (m *OperationReq) String() string { return proto.CompactTextString(m) }
func (*OperationReq) ProtoMessage()    {}
func (*OperationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_901fdf95822f51d8, []int{4}
}
func (m *OperationReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OperationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OperationReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OperationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationReq.Merge(m, src)
}
func (m *OperationReq) XXX_Size() int {
	return m.Size()
}
func (m *OperationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationReq.DiscardUnknown(m)
}

var xxx_messageInfo_OperationReq proto.InternalMessageInfo

func (m *OperationReq) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *OperationReq) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

// 通知客户端断开连接的消息
type KickNotify struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=uid" json:"uid"`
	Reason               int32    `protobuf:"varint,2,opt,name=reason" json:"reason"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickNotify) Reset()         { *m = KickNotify{} }
func (m *KickNotify) String() string { return proto.CompactTextString(m) }
func (*KickNotify) ProtoMessage()    {}
func (*KickNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_901fdf95822f51d8, []int{5}
}
func (m *KickNotify) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KickNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KickNotify.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KickNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickNotify.Merge(m, src)
}
func (m *KickNotify) XXX_Size() int {
	return m.Size()
}
func (m *KickNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_KickNotify.DiscardUnknown(m)
}

var xxx_messageInfo_KickNotify proto.InternalMessageInfo

func (m *KickNotify) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *KickNotify) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

// 批量RPC通用响应消息-此消息内容必须相同
type RPCBatchResponse struct {
	Response             bool     `protobuf:"varint,1,opt,name=Response" json:"Response"`
	SrvName              string   `protobuf:"bytes,2,opt,name=SrvName" json:"SrvName"`
	SrvID                int32    `protobuf:"varint,3,opt,name=SrvID" json:"SrvID"`
	UIDList              []int32  `protobuf:"varint,4,rep,name=UIDList" json:"UIDList,omitempty"`
	Seq                  int32    `protobuf:"varint,5,opt,name=Seq" json:"Seq"`
	Code                 int32    `protobuf:"varint,6,opt,name=Code" json:"Code"`
	Cmd                  int32    `protobuf:"varint,7,opt,name=Cmd" json:"Cmd"`
	Payload              []byte   `protobuf:"bytes,8,opt,name=Payload" json:"Payload"`
	Token                string   `protobuf:"bytes,9,opt,name=Token" json:"Token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCBatchResponse) Reset()         { *m = RPCBatchResponse{} }
func (m *RPCBatchResponse) String() string { return proto.CompactTextString(m) }
func (*RPCBatchResponse) ProtoMessage()    {}
func (*RPCBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_901fdf95822f51d8, []int{6}
}
func (m *RPCBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RPCBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RPCBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RPCBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCBatchResponse.Merge(m, src)
}
func (m *RPCBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *RPCBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RPCBatchResponse proto.InternalMessageInfo

func (m *RPCBatchResponse) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

func (m *RPCBatchResponse) GetSrvName() string {
	if m != nil {
		return m.SrvName
	}
	return ""
}

func (m *RPCBatchResponse) GetSrvID() int32 {
	if m != nil {
		return m.SrvID
	}
	return 0
}

func (m *RPCBatchResponse) GetUIDList() []int32 {
	if m != nil {
		return m.UIDList
	}
	return nil
}

func (m *RPCBatchResponse) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *RPCBatchResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RPCBatchResponse) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *RPCBatchResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RPCBatchResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RPCBatchResponseRow struct {
	Uid                  int32    `protobuf:"varint,1,opt,name=Uid" json:"Uid"`
	Code                 int32    `protobuf:"varint,2,opt,name=Code" json:"Code"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCBatchResponseRow) Reset()         { *m = RPCBatchResponseRow{} }
func (m *RPCBatchResponseRow) String() string { return proto.CompactTextString(m) }
func (*RPCBatchResponseRow) ProtoMessage()    {}
func (*RPCBatchResponseRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_901fdf95822f51d8, []int{7}
}
func (m *RPCBatchResponseRow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RPCBatchResponseRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RPCBatchResponseRow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RPCBatchResponseRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCBatchResponseRow.Merge(m, src)
}
func (m *RPCBatchResponseRow) XXX_Size() int {
	return m.Size()
}
func (m *RPCBatchResponseRow) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCBatchResponseRow.DiscardUnknown(m)
}

var xxx_messageInfo_RPCBatchResponseRow proto.InternalMessageInfo

func (m *RPCBatchResponseRow) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RPCBatchResponseRow) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// 批量消息结果
type RPCBatchResponseResult struct {
	Results              []*RPCBatchResponseRow `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RPCBatchResponseResult) Reset()         { *m = RPCBatchResponseResult{} }
func (m *RPCBatchResponseResult) String() string { return proto.CompactTextString(m) }
func (*RPCBatchResponseResult) ProtoMessage()    {}
func (*RPCBatchResponseResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_901fdf95822f51d8, []int{8}
}
func (m *RPCBatchResponseResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RPCBatchResponseResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RPCBatchResponseResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RPCBatchResponseResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCBatchResponseResult.Merge(m, src)
}
func (m *RPCBatchResponseResult) XXX_Size() int {
	return m.Size()
}
func (m *RPCBatchResponseResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCBatchResponseResult.DiscardUnknown(m)
}

var xxx_messageInfo_RPCBatchResponseResult proto.InternalMessageInfo

func (m *RPCBatchResponseResult) GetResults() []*RPCBatchResponseRow {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "protoAccess.RPCRequest")
	proto.RegisterType((*RPCResponse)(nil), "protoAccess.RPCResponse")
	proto.RegisterType((*SetUIDReq)(nil), "protoAccess.SetUIDReq")
	proto.RegisterType((*SetUIDRsp)(nil), "protoAccess.SetUIDRsp")
	proto.RegisterType((*OperationReq)(nil), "protoAccess.OperationReq")
	proto.RegisterType((*KickNotify)(nil), "protoAccess.KickNotify")
	proto.RegisterType((*RPCBatchResponse)(nil), "protoAccess.RPCBatchResponse")
	proto.RegisterType((*RPCBatchResponseRow)(nil), "protoAccess.RPCBatchResponseRow")
	proto.RegisterType((*RPCBatchResponseResult)(nil), "protoAccess.RPCBatchResponseResult")
}

func init() { proto.RegisterFile("access/access.proto", fileDescriptor_901fdf95822f51d8) }

var fileDescriptor_901fdf95822f51d8 = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xeb, 0x7f, 0x4d, 0x3a, 0xe9, 0x4f, 0xbf, 0xca, 0x95, 0xaa, 0x55, 0x84, 0x8c, 0x65,
	0x71, 0x88, 0x90, 0x48, 0x24, 0x8e, 0x48, 0x48, 0x34, 0x36, 0x20, 0x0b, 0x28, 0x91, 0xd3, 0x3c,
	0x80, 0x6b, 0x6f, 0x52, 0x2b, 0x8d, 0x37, 0xf5, 0xae, 0x03, 0x7d, 0x05, 0xb8, 0x70, 0xe4, 0x91,
	0x7a, 0x44, 0xe2, 0x8e, 0x50, 0x78, 0x11, 0xb4, 0xeb, 0x3f, 0xd9, 0xb8, 0xa9, 0xc4, 0x09, 0x71,
	0xf2, 0xee, 0x67, 0x67, 0xa6, 0x33, 0xdf, 0xef, 0x34, 0x70, 0x1c, 0x46, 0x11, 0xa6, 0x74, 0x50,
	0x7c, 0xfa, 0xcb, 0x8c, 0x30, 0x62, 0x76, 0xc4, 0xe7, 0x54, 0xa0, 0xee, 0x93, 0x59, 0xc2, 0x2e,
	0xf3, 0x8b, 0x7e, 0x44, 0x16, 0x83, 0x19, 0x99, 0x91, 0x81, 0x78, 0xbc, 0xc8, 0xa7, 0xe2, 0x26,
	0x2e, 0xe2, 0x54, 0xe4, 0x3a, 0x9f, 0x34, 0x80, 0x60, 0xe4, 0x06, 0xf8, 0x3a, 0xc7, 0x94, 0x99,
	0x36, 0xb4, 0x03, 0xbc, 0x20, 0x0c, 0xfb, 0x23, 0xa4, 0xd8, 0x4a, 0xef, 0x60, 0xa8, 0xdf, 0xfe,
	0x78, 0xb8, 0x17, 0xd4, 0xd4, 0x7c, 0x04, 0x50, 0x9c, 0x47, 0x24, 0x63, 0x48, 0xb5, 0x95, 0x9e,
	0x51, 0xc6, 0x48, 0x9c, 0xd7, 0x39, 0x8d, 0xa2, 0x71, 0xb6, 0xf2, 0x3d, 0xa4, 0x49, 0x31, 0x35,
	0x35, 0x4f, 0x40, 0x1b, 0xe3, 0x6b, 0xa4, 0x4b, 0x8f, 0x1c, 0x70, 0x3e, 0xf1, 0x3d, 0x64, 0xc8,
	0x7c, 0xe2, 0x7b, 0xa6, 0x05, 0xad, 0x51, 0x78, 0x73, 0x45, 0xc2, 0x18, 0xed, 0xdb, 0x4a, 0xef,
	0xb0, 0x7c, 0xab, 0x20, 0xef, 0x6b, 0x8c, 0xb3, 0x15, 0xce, 0xce, 0xc2, 0x05, 0x46, 0x2d, 0xa9,
	0x77, 0x89, 0xf3, 0xbe, 0x5e, 0xe5, 0x69, 0x24, 0x62, 0xda, 0xf2, 0x7c, 0x15, 0x35, 0xfb, 0xf0,
	0x7f, 0x80, 0xa7, 0x38, 0xc3, 0x59, 0x91, 0xe6, 0x7b, 0xe8, 0x40, 0xea, 0xa5, 0xf9, 0x68, 0x3e,
	0x86, 0xff, 0xb6, 0x10, 0x02, 0xa9, 0xec, 0xf6, 0x13, 0x9f, 0xe1, 0xe5, 0x47, 0xe6, 0x85, 0x2c,
	0x44, 0x1d, 0x29, 0xaa, 0x82, 0xce, 0x77, 0x15, 0x3a, 0xc2, 0x0c, 0xba, 0x24, 0x29, 0xc5, 0x85,
	0x1b, 0xc5, 0x59, 0xb8, 0xd1, 0xde, 0xb8, 0x51, 0x46, 0x58, 0xd0, 0x1a, 0x67, 0x2b, 0x31, 0x8e,
	0x2a, 0x57, 0x2c, 0xa1, 0xd9, 0x05, 0xe3, 0xae, 0x09, 0x46, 0xed, 0x00, 0x57, 0x5a, 0x6f, 0x2a,
	0x5d, 0x3a, 0x63, 0x34, 0x9d, 0x41, 0xa0, 0xbb, 0x24, 0xc6, 0x42, 0xfe, 0xea, 0x41, 0x10, 0x9e,
	0xe1, 0x2e, 0x62, 0x21, 0x7a, 0x9d, 0xe1, 0x2e, 0x62, 0xd9, 0xb3, 0xf6, 0x2e, 0xcf, 0xba, 0x60,
	0x9c, 0x93, 0x39, 0x4e, 0x85, 0xc2, 0x55, 0xef, 0x05, 0x32, 0x1d, 0x38, 0x18, 0x63, 0xe6, 0x12,
	0x32, 0x4f, 0xb0, 0xd0, 0xb4, 0x1a, 0x7e, 0x83, 0xb9, 0xe7, 0x5e, 0x42, 0x23, 0x92, 0xa6, 0x38,
	0x62, 0xe8, 0x50, 0x0a, 0x92, 0xb8, 0xf3, 0x59, 0x11, 0xa5, 0x26, 0xbe, 0x17, 0x6c, 0xf6, 0x4b,
	0x69, 0x4e, 0x2d, 0x6f, 0xbe, 0xfa, 0x07, 0x9b, 0xaf, 0xdd, 0xb3, 0xf9, 0x92, 0xc7, 0xfa, 0x2e,
	0x8f, 0x9f, 0xd7, 0xcd, 0xd0, 0x65, 0x2d, 0xa9, 0xb2, 0x4b, 0xd2, 0x77, 0x74, 0xb6, 0xd5, 0x09,
	0x07, 0xce, 0x0b, 0x38, 0x7c, 0xbf, 0xc4, 0x59, 0xc8, 0x12, 0x92, 0x96, 0xe3, 0xe4, 0x49, 0xbc,
	0x3d, 0x4e, 0x9e, 0xc4, 0xbc, 0x72, 0x92, 0x4e, 0x89, 0x28, 0x50, 0xe9, 0x2e, 0x88, 0x33, 0x04,
	0x78, 0x93, 0x44, 0xf3, 0x33, 0xc2, 0x92, 0xe9, 0xcd, 0xbd, 0xf9, 0x0f, 0x60, 0x3f, 0xc3, 0x21,
	0x25, 0xe9, 0xd6, 0xbf, 0x78, 0xc9, 0x9c, 0x2f, 0x2a, 0x1c, 0x05, 0x23, 0x77, 0x18, 0xb2, 0xe8,
	0xf2, 0x2f, 0x6d, 0x2b, 0x82, 0xd6, 0xc4, 0xf7, 0xde, 0x26, 0x94, 0x21, 0xdd, 0xd6, 0x7a, 0x46,
	0x50, 0x5d, 0xff, 0x8d, 0x7d, 0x75, 0x5e, 0xc3, 0x71, 0x53, 0x91, 0x80, 0x7c, 0x10, 0xeb, 0xd6,
	0xd4, 0x77, 0x52, 0xf8, 0x23, 0x9a, 0x53, 0x9b, 0xcd, 0x39, 0xe7, 0x70, 0x72, 0xa7, 0x10, 0xa6,
	0xf9, 0x15, 0x33, 0x9f, 0x41, 0x2b, 0x13, 0x27, 0x8a, 0x14, 0x5b, 0xeb, 0x75, 0x9e, 0xda, 0x7d,
	0xe9, 0x97, 0xbf, 0xbf, 0xe3, 0xcf, 0x07, 0x55, 0xc2, 0xf0, 0xe8, 0x76, 0x6d, 0x29, 0xdf, 0xd6,
	0x96, 0xf2, 0x73, 0x6d, 0x29, 0x5f, 0x7f, 0x59, 0x7b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x34,
	0x7d, 0xea, 0x9c, 0x4b, 0x06, 0x00, 0x00,
}

func (m *RPCRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RPCRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RPCRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	i -= len(m.ExtData)
	copy(dAtA[i:], m.ExtData)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.ExtData)))
	i--
	dAtA[i] = 0x5a
	i -= len(m.RefererServer)
	copy(dAtA[i:], m.RefererServer)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.RefererServer)))
	i--
	dAtA[i] = 0x52
	i = encodeVarintAccess(dAtA, i, uint64(m.RefererServerID))
	i--
	dAtA[i] = 0x48
	i -= len(m.FuncName)
	copy(dAtA[i:], m.FuncName)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.FuncName)))
	i--
	dAtA[i] = 0x42
	i -= len(m.ServerName)
	copy(dAtA[i:], m.ServerName)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.ServerName)))
	i--
	dAtA[i] = 0x3a
	if m.Payload != nil {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintAccess(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x32
	}
	i = encodeVarintAccess(dAtA, i, uint64(m.UID))
	i--
	dAtA[i] = 0x28
	i = encodeVarintAccess(dAtA, i, uint64(m.Seq))
	i--
	dAtA[i] = 0x20
	i = encodeVarintAccess(dAtA, i, uint64(m.AccSrvID))
	i--
	dAtA[i] = 0x18
	i = encodeVarintAccess(dAtA, i, uint64(m.RemotePort))
	i--
	dAtA[i] = 0x10
	i -= len(m.RemoteIP)
	copy(dAtA[i:], m.RemoteIP)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.RemoteIP)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *RPCResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RPCResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RPCResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	i--
	if m.Disconnect {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x60
	i--
	if m.SetCookie {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x50
	i -= len(m.Token)
	copy(dAtA[i:], m.Token)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.Token)))
	i--
	dAtA[i] = 0x4a
	if m.Payload != nil {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintAccess(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x42
	}
	i = encodeVarintAccess(dAtA, i, uint64(m.Cmd))
	i--
	dAtA[i] = 0x38
	i = encodeVarintAccess(dAtA, i, uint64(m.Code))
	i--
	dAtA[i] = 0x30
	i = encodeVarintAccess(dAtA, i, uint64(m.Seq))
	i--
	dAtA[i] = 0x28
	i = encodeVarintAccess(dAtA, i, uint64(m.UID))
	i--
	dAtA[i] = 0x20
	i = encodeVarintAccess(dAtA, i, uint64(m.SrvID))
	i--
	dAtA[i] = 0x18
	i -= len(m.SrvName)
	copy(dAtA[i:], m.SrvName)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.SrvName)))
	i--
	dAtA[i] = 0x12
	i--
	if m.Response {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *SetUIDReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetUIDReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetUIDReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	i -= len(m.ExtData)
	copy(dAtA[i:], m.ExtData)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.ExtData)))
	i--
	dAtA[i] = 0x22
	i = encodeVarintAccess(dAtA, i, uint64(m.RemotePort))
	i--
	dAtA[i] = 0x18
	i -= len(m.RemoteIP)
	copy(dAtA[i:], m.RemoteIP)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.RemoteIP)))
	i--
	dAtA[i] = 0x12
	i = encodeVarintAccess(dAtA, i, uint64(m.UID))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *SetUIDRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetUIDRsp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetUIDRsp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	i -= len(m.Msg)
	copy(dAtA[i:], m.Msg)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.Msg)))
	i--
	dAtA[i] = 0x12
	i = encodeVarintAccess(dAtA, i, uint64(m.Code))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *OperationReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OperationReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OperationReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Info != nil {
		i -= len(m.Info)
		copy(dAtA[i:], m.Info)
		i = encodeVarintAccess(dAtA, i, uint64(len(m.Info)))
		i--
		dAtA[i] = 0x12
	}
	i = encodeVarintAccess(dAtA, i, uint64(m.Uid))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *KickNotify) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KickNotify) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KickNotify) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	i = encodeVarintAccess(dAtA, i, uint64(m.Reason))
	i--
	dAtA[i] = 0x10
	i = encodeVarintAccess(dAtA, i, uint64(m.Uid))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *RPCBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RPCBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RPCBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	i -= len(m.Token)
	copy(dAtA[i:], m.Token)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.Token)))
	i--
	dAtA[i] = 0x4a
	if m.Payload != nil {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintAccess(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x42
	}
	i = encodeVarintAccess(dAtA, i, uint64(m.Cmd))
	i--
	dAtA[i] = 0x38
	i = encodeVarintAccess(dAtA, i, uint64(m.Code))
	i--
	dAtA[i] = 0x30
	i = encodeVarintAccess(dAtA, i, uint64(m.Seq))
	i--
	dAtA[i] = 0x28
	if len(m.UIDList) > 0 {
		for iNdEx := len(m.UIDList) - 1; iNdEx >= 0; iNdEx-- {
			i = encodeVarintAccess(dAtA, i, uint64(m.UIDList[iNdEx]))
			i--
			dAtA[i] = 0x20
		}
	}
	i = encodeVarintAccess(dAtA, i, uint64(m.SrvID))
	i--
	dAtA[i] = 0x18
	i -= len(m.SrvName)
	copy(dAtA[i:], m.SrvName)
	i = encodeVarintAccess(dAtA, i, uint64(len(m.SrvName)))
	i--
	dAtA[i] = 0x12
	i--
	if m.Response {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *RPCBatchResponseRow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RPCBatchResponseRow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RPCBatchResponseRow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	i = encodeVarintAccess(dAtA, i, uint64(m.Code))
	i--
	dAtA[i] = 0x10
	i = encodeVarintAccess(dAtA, i, uint64(m.Uid))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *RPCBatchResponseResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RPCBatchResponseResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RPCBatchResponseResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Results) > 0 {
		for iNdEx := len(m.Results) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Results[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAccess(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintAccess(dAtA []byte, offset int, v uint64) int {
	offset -= sovAccess(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RPCRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RemoteIP)
	n += 1 + l + sovAccess(uint64(l))
	n += 1 + sovAccess(uint64(m.RemotePort))
	n += 1 + sovAccess(uint64(m.AccSrvID))
	n += 1 + sovAccess(uint64(m.Seq))
	n += 1 + sovAccess(uint64(m.UID))
	if m.Payload != nil {
		l = len(m.Payload)
		n += 1 + l + sovAccess(uint64(l))
	}
	l = len(m.ServerName)
	n += 1 + l + sovAccess(uint64(l))
	l = len(m.FuncName)
	n += 1 + l + sovAccess(uint64(l))
	n += 1 + sovAccess(uint64(m.RefererServerID))
	l = len(m.RefererServer)
	n += 1 + l + sovAccess(uint64(l))
	l = len(m.ExtData)
	n += 1 + l + sovAccess(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RPCResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2
	l = len(m.SrvName)
	n += 1 + l + sovAccess(uint64(l))
	n += 1 + sovAccess(uint64(m.SrvID))
	n += 1 + sovAccess(uint64(m.UID))
	n += 1 + sovAccess(uint64(m.Seq))
	n += 1 + sovAccess(uint64(m.Code))
	n += 1 + sovAccess(uint64(m.Cmd))
	if m.Payload != nil {
		l = len(m.Payload)
		n += 1 + l + sovAccess(uint64(l))
	}
	l = len(m.Token)
	n += 1 + l + sovAccess(uint64(l))
	n += 2
	n += 2
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SetUIDReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovAccess(uint64(m.UID))
	l = len(m.RemoteIP)
	n += 1 + l + sovAccess(uint64(l))
	n += 1 + sovAccess(uint64(m.RemotePort))
	l = len(m.ExtData)
	n += 1 + l + sovAccess(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SetUIDRsp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovAccess(uint64(m.Code))
	l = len(m.Msg)
	n += 1 + l + sovAccess(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *OperationReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovAccess(uint64(m.Uid))
	if m.Info != nil {
		l = len(m.Info)
		n += 1 + l + sovAccess(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *KickNotify) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovAccess(uint64(m.Uid))
	n += 1 + sovAccess(uint64(m.Reason))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RPCBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2
	l = len(m.SrvName)
	n += 1 + l + sovAccess(uint64(l))
	n += 1 + sovAccess(uint64(m.SrvID))
	if len(m.UIDList) > 0 {
		for _, e := range m.UIDList {
			n += 1 + sovAccess(uint64(e))
		}
	}
	n += 1 + sovAccess(uint64(m.Seq))
	n += 1 + sovAccess(uint64(m.Code))
	n += 1 + sovAccess(uint64(m.Cmd))
	if m.Payload != nil {
		l = len(m.Payload)
		n += 1 + l + sovAccess(uint64(l))
	}
	l = len(m.Token)
	n += 1 + l + sovAccess(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RPCBatchResponseRow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovAccess(uint64(m.Uid))
	n += 1 + sovAccess(uint64(m.Code))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RPCBatchResponseResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Results) > 0 {
		for _, e := range m.Results {
			l = e.Size()
			n += 1 + l + sovAccess(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovAccess(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAccess(x uint64) (n int) {
	return sovAccess(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RPCRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RPCRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RPCRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemotePort", wireType)
			}
			m.RemotePort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemotePort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccSrvID", wireType)
			}
			m.AccSrvID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccSrvID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			m.UID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FuncName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FuncName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefererServerID", wireType)
			}
			m.RefererServerID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RefererServerID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefererServer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefererServer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccess(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccess
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RPCResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RPCResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RPCResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Response = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrvName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrvName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrvID", wireType)
			}
			m.SrvID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrvID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			m.UID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetCookie", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SetCookie = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Disconnect", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Disconnect = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAccess(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccess
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetUIDReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetUIDReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetUIDReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			m.UID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteIP", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteIP = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemotePort", wireType)
			}
			m.RemotePort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemotePort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccess(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccess
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetUIDRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetUIDRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetUIDRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccess(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccess
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OperationReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OperationReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OperationReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			m.Uid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = append(m.Info[:0], dAtA[iNdEx:postIndex]...)
			if m.Info == nil {
				m.Info = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccess(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccess
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KickNotify) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KickNotify: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KickNotify: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			m.Uid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			m.Reason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reason |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAccess(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccess
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RPCBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RPCBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RPCBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Response = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrvName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrvName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrvID", wireType)
			}
			m.SrvID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrvID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAccess
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.UIDList = append(m.UIDList, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAccess
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthAccess
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthAccess
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.UIDList) == 0 {
					m.UIDList = make([]int32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAccess
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.UIDList = append(m.UIDList, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field UIDList", wireType)
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cmd |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccess(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccess
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RPCBatchResponseRow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RPCBatchResponseRow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RPCBatchResponseRow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			m.Uid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAccess(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccess
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RPCBatchResponseResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RPCBatchResponseResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RPCBatchResponseResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Results", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAccess
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAccess
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Results = append(m.Results, &RPCBatchResponseRow{})
			if err := m.Results[len(m.Results)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccess(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAccess
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAccess(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAccess
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccess
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAccess
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAccess
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAccess
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAccess        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAccess          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAccess = fmt.Errorf("proto: unexpected end of group")
)
