// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clientTrans/clientTrans.proto

package clientTrans

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Xextend struct {
	SrvId                *int32   `protobuf:"varint,1,opt,name=SrvId" json:"SrvId,omitempty"`
	TableId              *int64   `protobuf:"varint,2,opt,name=TableId" json:"TableId,omitempty"`
	Extend1              *int64   `protobuf:"varint,3,opt,name=Extend1" json:"Extend1,omitempty"`
	Extend2              *int64   `protobuf:"varint,4,opt,name=Extend2" json:"Extend2,omitempty"`
	SrvName              *string  `protobuf:"bytes,5,opt,name=SrvName" json:"SrvName,omitempty"`
	ExtPayLoad           []byte   `protobuf:"bytes,6,opt,name=ExtPayLoad" json:"ExtPayLoad,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Xextend) Reset()         { *m = Xextend{} }
func (m *Xextend) String() string { return proto.CompactTextString(m) }
func (*Xextend) ProtoMessage()    {}
func (*Xextend) Descriptor() ([]byte, []int) {
	return fileDescriptor_444eb219003c8eaa, []int{0}
}
func (m *Xextend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Xextend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Xextend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Xextend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Xextend.Merge(m, src)
}
func (m *Xextend) XXX_Size() int {
	return m.Size()
}
func (m *Xextend) XXX_DiscardUnknown() {
	xxx_messageInfo_Xextend.DiscardUnknown(m)
}

var xxx_messageInfo_Xextend proto.InternalMessageInfo

func (m *Xextend) GetSrvId() int32 {
	if m != nil && m.SrvId != nil {
		return *m.SrvId
	}
	return 0
}

func (m *Xextend) GetTableId() int64 {
	if m != nil && m.TableId != nil {
		return *m.TableId
	}
	return 0
}

func (m *Xextend) GetExtend1() int64 {
	if m != nil && m.Extend1 != nil {
		return *m.Extend1
	}
	return 0
}

func (m *Xextend) GetExtend2() int64 {
	if m != nil && m.Extend2 != nil {
		return *m.Extend2
	}
	return 0
}

func (m *Xextend) GetSrvName() string {
	if m != nil && m.SrvName != nil {
		return *m.SrvName
	}
	return ""
}

func (m *Xextend) GetExtPayLoad() []byte {
	if m != nil {
		return m.ExtPayLoad
	}
	return nil
}

type Xcodec struct {
	MsgInfoK             []byte   `protobuf:"bytes,1,opt,name=MsgInfoK" json:"MsgInfoK,omitempty"`
	Version              *int32   `protobuf:"varint,2,opt,name=Version" json:"Version,omitempty"`
	MsgInfoA             []byte   `protobuf:"bytes,3,opt,name=MsgInfoA" json:"MsgInfoA,omitempty"`
	Seq                  *int32   `protobuf:"varint,4,opt,name=Seq" json:"Seq,omitempty"`
	MsgInfoB             []byte   `protobuf:"bytes,5,opt,name=MsgInfoB" json:"MsgInfoB,omitempty"`
	SvnName              *string  `protobuf:"bytes,6,opt,name=SvnName" json:"SvnName,omitempty"`
	MsgInfoC             []byte   `protobuf:"bytes,7,opt,name=MsgInfoC" json:"MsgInfoC,omitempty"`
	FuncName             *string  `protobuf:"bytes,8,opt,name=FuncName" json:"FuncName,omitempty"`
	MsgInfoD             []byte   `protobuf:"bytes,9,opt,name=MsgInfoD" json:"MsgInfoD,omitempty"`
	Code                 *int32   `protobuf:"varint,10,opt,name=Code" json:"Code,omitempty"`
	MsgInfoE             []byte   `protobuf:"bytes,11,opt,name=MsgInfoE" json:"MsgInfoE,omitempty"`
	Cmd                  *int32   `protobuf:"varint,12,opt,name=Cmd" json:"Cmd,omitempty"`
	MsgInfoF             []byte   `protobuf:"bytes,13,opt,name=MsgInfoF" json:"MsgInfoF,omitempty"`
	Token                []byte   `protobuf:"bytes,14,opt,name=Token" json:"Token,omitempty"`
	MsgInfoG             []byte   `protobuf:"bytes,15,opt,name=MsgInfoG" json:"MsgInfoG,omitempty"`
	PayLoad              []byte   `protobuf:"bytes,16,opt,name=PayLoad" json:"PayLoad,omitempty"`
	MsgInfoH             []byte   `protobuf:"bytes,17,opt,name=MsgInfoH" json:"MsgInfoH,omitempty"`
	Cookies              []byte   `protobuf:"bytes,18,opt,name=Cookies" json:"Cookies,omitempty"`
	MsgInfoI             []byte   `protobuf:"bytes,19,opt,name=MsgInfoI" json:"MsgInfoI,omitempty"`
	ExtendBytes          []byte   `protobuf:"bytes,20,opt,name=ExtendBytes" json:"ExtendBytes,omitempty"`
	MsgInfoJ             []byte   `protobuf:"bytes,21,opt,name=MsgInfoJ" json:"MsgInfoJ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Xcodec) Reset()         { *m = Xcodec{} }
func (m *Xcodec) String() string { return proto.CompactTextString(m) }
func (*Xcodec) ProtoMessage()    {}
func (*Xcodec) Descriptor() ([]byte, []int) {
	return fileDescriptor_444eb219003c8eaa, []int{1}
}
func (m *Xcodec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Xcodec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Xcodec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Xcodec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Xcodec.Merge(m, src)
}
func (m *Xcodec) XXX_Size() int {
	return m.Size()
}
func (m *Xcodec) XXX_DiscardUnknown() {
	xxx_messageInfo_Xcodec.DiscardUnknown(m)
}

var xxx_messageInfo_Xcodec proto.InternalMessageInfo

func (m *Xcodec) GetMsgInfoK() []byte {
	if m != nil {
		return m.MsgInfoK
	}
	return nil
}

func (m *Xcodec) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Xcodec) GetMsgInfoA() []byte {
	if m != nil {
		return m.MsgInfoA
	}
	return nil
}

func (m *Xcodec) GetSeq() int32 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *Xcodec) GetMsgInfoB() []byte {
	if m != nil {
		return m.MsgInfoB
	}
	return nil
}

func (m *Xcodec) GetSvnName() string {
	if m != nil && m.SvnName != nil {
		return *m.SvnName
	}
	return ""
}

func (m *Xcodec) GetMsgInfoC() []byte {
	if m != nil {
		return m.MsgInfoC
	}
	return nil
}

func (m *Xcodec) GetFuncName() string {
	if m != nil && m.FuncName != nil {
		return *m.FuncName
	}
	return ""
}

func (m *Xcodec) GetMsgInfoD() []byte {
	if m != nil {
		return m.MsgInfoD
	}
	return nil
}

func (m *Xcodec) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Xcodec) GetMsgInfoE() []byte {
	if m != nil {
		return m.MsgInfoE
	}
	return nil
}

func (m *Xcodec) GetCmd() int32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *Xcodec) GetMsgInfoF() []byte {
	if m != nil {
		return m.MsgInfoF
	}
	return nil
}

func (m *Xcodec) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Xcodec) GetMsgInfoG() []byte {
	if m != nil {
		return m.MsgInfoG
	}
	return nil
}

func (m *Xcodec) GetPayLoad() []byte {
	if m != nil {
		return m.PayLoad
	}
	return nil
}

func (m *Xcodec) GetMsgInfoH() []byte {
	if m != nil {
		return m.MsgInfoH
	}
	return nil
}

func (m *Xcodec) GetCookies() []byte {
	if m != nil {
		return m.Cookies
	}
	return nil
}

func (m *Xcodec) GetMsgInfoI() []byte {
	if m != nil {
		return m.MsgInfoI
	}
	return nil
}

func (m *Xcodec) GetExtendBytes() []byte {
	if m != nil {
		return m.ExtendBytes
	}
	return nil
}

func (m *Xcodec) GetMsgInfoJ() []byte {
	if m != nil {
		return m.MsgInfoJ
	}
	return nil
}

func init() {
	proto.RegisterType((*Xextend)(nil), "clientTrans.Xextend")
	proto.RegisterType((*Xcodec)(nil), "clientTrans.Xcodec")
}

func init() { proto.RegisterFile("clientTrans/clientTrans.proto", fileDescriptor_444eb219003c8eaa) }

var fileDescriptor_444eb219003c8eaa = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xdd, 0x6e, 0xda, 0x30,
	0x1c, 0xc5, 0xe7, 0x41, 0xf8, 0x30, 0x6c, 0x63, 0x1e, 0x93, 0xfe, 0x9a, 0xb4, 0x28, 0xe2, 0x2a,
	0x57, 0x9b, 0xc6, 0x1b, 0x90, 0x10, 0x20, 0xec, 0x43, 0x53, 0x40, 0x15, 0xb7, 0x69, 0xec, 0x56,
	0x08, 0xb0, 0xdb, 0x24, 0x45, 0xf0, 0x26, 0x7d, 0x83, 0xde, 0xf6, 0x31, 0x7a, 0xd9, 0x47, 0xa8,
	0xe8, 0x8b, 0x54, 0x76, 0x08, 0xd8, 0x77, 0x3e, 0x3e, 0xe7, 0xa7, 0x9c, 0x23, 0x07, 0x7f, 0x4f,
	0xd6, 0x4b, 0xc6, 0xf3, 0x79, 0x1a, 0xf3, 0xec, 0xa7, 0x76, 0xfe, 0x71, 0x93, 0x8a, 0x5c, 0x90,
	0x96, 0x76, 0xd5, 0x7b, 0x40, 0xb8, 0xbe, 0x60, 0xbb, 0x9c, 0x71, 0x4a, 0xba, 0xd8, 0x9a, 0xa5,
	0xdb, 0x90, 0x02, 0x72, 0x90, 0x6b, 0x45, 0x85, 0x20, 0x80, 0xeb, 0xf3, 0xf8, 0x72, 0xcd, 0x42,
	0x0a, 0xef, 0x1d, 0xe4, 0x56, 0xa2, 0x52, 0x4a, 0x27, 0x50, 0xe4, 0x2f, 0xa8, 0x14, 0xce, 0x51,
	0x9e, 0x9d, 0x3e, 0x54, 0x75, 0xa7, 0x2f, 0x9d, 0x59, 0xba, 0xfd, 0x17, 0x6f, 0x18, 0x58, 0x0e,
	0x72, 0x9b, 0x51, 0x29, 0x89, 0x8d, 0x71, 0xb0, 0xcb, 0xff, 0xc7, 0xfb, 0x3f, 0x22, 0xa6, 0x50,
	0x73, 0x90, 0xdb, 0x8e, 0xb4, 0x9b, 0xde, 0x63, 0x15, 0xd7, 0x16, 0x89, 0xa0, 0x2c, 0x21, 0xdf,
	0x70, 0xe3, 0x6f, 0x76, 0x1d, 0xf2, 0x2b, 0xf1, 0x5b, 0x75, 0x6d, 0x47, 0x27, 0x2d, 0x3f, 0x70,
	0xc1, 0xd2, 0x6c, 0x29, 0xb8, 0xaa, 0x6b, 0x45, 0xa5, 0xd4, 0xa8, 0x81, 0xea, 0x7b, 0xa6, 0x06,
	0xa4, 0x83, 0x2b, 0x33, 0x76, 0xab, 0xca, 0x5a, 0x91, 0x3c, 0x6a, 0x69, 0x4f, 0x35, 0x3d, 0xa7,
	0x3d, 0x35, 0x62, 0xcb, 0xd5, 0x88, 0xda, 0x71, 0x44, 0x21, 0x35, 0xca, 0x87, 0xba, 0x41, 0xf9,
	0xd2, 0x1b, 0xdd, 0xf1, 0x44, 0x61, 0x0d, 0x85, 0x9d, 0xb4, 0xc6, 0x0d, 0xa1, 0x69, 0x70, 0x43,
	0x42, 0x70, 0xd5, 0x17, 0x94, 0x01, 0x56, 0xe5, 0xd4, 0x59, 0xcb, 0x07, 0xd0, 0x32, 0xf2, 0x81,
	0xdc, 0xe2, 0x6f, 0x28, 0xb4, 0x8b, 0x2d, 0xfe, 0x86, 0x6a, 0xe9, 0x11, 0x7c, 0x30, 0xd2, 0x23,
	0xf9, 0xe8, 0x73, 0xb1, 0x62, 0x1c, 0x3e, 0x2a, 0xa3, 0x10, 0x1a, 0x31, 0x86, 0x4f, 0x06, 0x31,
	0x96, 0xeb, 0xcb, 0x57, 0xea, 0x28, 0xab, 0x94, 0x1a, 0x35, 0x81, 0xcf, 0x06, 0x35, 0x91, 0x94,
	0x2f, 0xc4, 0x6a, 0xc9, 0x32, 0x20, 0x05, 0x75, 0x94, 0x1a, 0x15, 0xc2, 0x17, 0x83, 0x0a, 0x89,
	0x83, 0x5b, 0xc5, 0x9f, 0xe3, 0xed, 0x73, 0x96, 0x41, 0x57, 0xd9, 0xfa, 0x95, 0x46, 0x4f, 0xe1,
	0xab, 0x41, 0x4f, 0xbd, 0xce, 0xd3, 0xc1, 0x46, 0xcf, 0x07, 0x1b, 0xbd, 0x1c, 0x6c, 0x74, 0xff,
	0x6a, 0xbf, 0x7b, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x40, 0x1f, 0x90, 0x4d, 0x1b, 0x03, 0x00, 0x00,
}

func (m *Xextend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Xextend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Xextend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.ExtPayLoad != nil {
		i -= len(m.ExtPayLoad)
		copy(dAtA[i:], m.ExtPayLoad)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.ExtPayLoad)))
		i--
		dAtA[i] = 0x32
	}
	if m.SrvName != nil {
		i -= len(*m.SrvName)
		copy(dAtA[i:], *m.SrvName)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(*m.SrvName)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Extend2 != nil {
		i = encodeVarintClientTrans(dAtA, i, uint64(*m.Extend2))
		i--
		dAtA[i] = 0x20
	}
	if m.Extend1 != nil {
		i = encodeVarintClientTrans(dAtA, i, uint64(*m.Extend1))
		i--
		dAtA[i] = 0x18
	}
	if m.TableId != nil {
		i = encodeVarintClientTrans(dAtA, i, uint64(*m.TableId))
		i--
		dAtA[i] = 0x10
	}
	if m.SrvId != nil {
		i = encodeVarintClientTrans(dAtA, i, uint64(*m.SrvId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Xcodec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Xcodec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Xcodec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.MsgInfoJ != nil {
		i -= len(m.MsgInfoJ)
		copy(dAtA[i:], m.MsgInfoJ)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoJ)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if m.ExtendBytes != nil {
		i -= len(m.ExtendBytes)
		copy(dAtA[i:], m.ExtendBytes)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.ExtendBytes)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.MsgInfoI != nil {
		i -= len(m.MsgInfoI)
		copy(dAtA[i:], m.MsgInfoI)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoI)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if m.Cookies != nil {
		i -= len(m.Cookies)
		copy(dAtA[i:], m.Cookies)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.Cookies)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.MsgInfoH != nil {
		i -= len(m.MsgInfoH)
		copy(dAtA[i:], m.MsgInfoH)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoH)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.PayLoad != nil {
		i -= len(m.PayLoad)
		copy(dAtA[i:], m.PayLoad)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.PayLoad)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.MsgInfoG != nil {
		i -= len(m.MsgInfoG)
		copy(dAtA[i:], m.MsgInfoG)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoG)))
		i--
		dAtA[i] = 0x7a
	}
	if m.Token != nil {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x72
	}
	if m.MsgInfoF != nil {
		i -= len(m.MsgInfoF)
		copy(dAtA[i:], m.MsgInfoF)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoF)))
		i--
		dAtA[i] = 0x6a
	}
	if m.Cmd != nil {
		i = encodeVarintClientTrans(dAtA, i, uint64(*m.Cmd))
		i--
		dAtA[i] = 0x60
	}
	if m.MsgInfoE != nil {
		i -= len(m.MsgInfoE)
		copy(dAtA[i:], m.MsgInfoE)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoE)))
		i--
		dAtA[i] = 0x5a
	}
	if m.Code != nil {
		i = encodeVarintClientTrans(dAtA, i, uint64(*m.Code))
		i--
		dAtA[i] = 0x50
	}
	if m.MsgInfoD != nil {
		i -= len(m.MsgInfoD)
		copy(dAtA[i:], m.MsgInfoD)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoD)))
		i--
		dAtA[i] = 0x4a
	}
	if m.FuncName != nil {
		i -= len(*m.FuncName)
		copy(dAtA[i:], *m.FuncName)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(*m.FuncName)))
		i--
		dAtA[i] = 0x42
	}
	if m.MsgInfoC != nil {
		i -= len(m.MsgInfoC)
		copy(dAtA[i:], m.MsgInfoC)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoC)))
		i--
		dAtA[i] = 0x3a
	}
	if m.SvnName != nil {
		i -= len(*m.SvnName)
		copy(dAtA[i:], *m.SvnName)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(*m.SvnName)))
		i--
		dAtA[i] = 0x32
	}
	if m.MsgInfoB != nil {
		i -= len(m.MsgInfoB)
		copy(dAtA[i:], m.MsgInfoB)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoB)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Seq != nil {
		i = encodeVarintClientTrans(dAtA, i, uint64(*m.Seq))
		i--
		dAtA[i] = 0x20
	}
	if m.MsgInfoA != nil {
		i -= len(m.MsgInfoA)
		copy(dAtA[i:], m.MsgInfoA)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoA)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Version != nil {
		i = encodeVarintClientTrans(dAtA, i, uint64(*m.Version))
		i--
		dAtA[i] = 0x10
	}
	if m.MsgInfoK != nil {
		i -= len(m.MsgInfoK)
		copy(dAtA[i:], m.MsgInfoK)
		i = encodeVarintClientTrans(dAtA, i, uint64(len(m.MsgInfoK)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintClientTrans(dAtA []byte, offset int, v uint64) int {
	offset -= sovClientTrans(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Xextend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SrvId != nil {
		n += 1 + sovClientTrans(uint64(*m.SrvId))
	}
	if m.TableId != nil {
		n += 1 + sovClientTrans(uint64(*m.TableId))
	}
	if m.Extend1 != nil {
		n += 1 + sovClientTrans(uint64(*m.Extend1))
	}
	if m.Extend2 != nil {
		n += 1 + sovClientTrans(uint64(*m.Extend2))
	}
	if m.SrvName != nil {
		l = len(*m.SrvName)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.ExtPayLoad != nil {
		l = len(m.ExtPayLoad)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Xcodec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgInfoK != nil {
		l = len(m.MsgInfoK)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.Version != nil {
		n += 1 + sovClientTrans(uint64(*m.Version))
	}
	if m.MsgInfoA != nil {
		l = len(m.MsgInfoA)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.Seq != nil {
		n += 1 + sovClientTrans(uint64(*m.Seq))
	}
	if m.MsgInfoB != nil {
		l = len(m.MsgInfoB)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.SvnName != nil {
		l = len(*m.SvnName)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.MsgInfoC != nil {
		l = len(m.MsgInfoC)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.FuncName != nil {
		l = len(*m.FuncName)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.MsgInfoD != nil {
		l = len(m.MsgInfoD)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.Code != nil {
		n += 1 + sovClientTrans(uint64(*m.Code))
	}
	if m.MsgInfoE != nil {
		l = len(m.MsgInfoE)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.Cmd != nil {
		n += 1 + sovClientTrans(uint64(*m.Cmd))
	}
	if m.MsgInfoF != nil {
		l = len(m.MsgInfoF)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.Token != nil {
		l = len(m.Token)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.MsgInfoG != nil {
		l = len(m.MsgInfoG)
		n += 1 + l + sovClientTrans(uint64(l))
	}
	if m.PayLoad != nil {
		l = len(m.PayLoad)
		n += 2 + l + sovClientTrans(uint64(l))
	}
	if m.MsgInfoH != nil {
		l = len(m.MsgInfoH)
		n += 2 + l + sovClientTrans(uint64(l))
	}
	if m.Cookies != nil {
		l = len(m.Cookies)
		n += 2 + l + sovClientTrans(uint64(l))
	}
	if m.MsgInfoI != nil {
		l = len(m.MsgInfoI)
		n += 2 + l + sovClientTrans(uint64(l))
	}
	if m.ExtendBytes != nil {
		l = len(m.ExtendBytes)
		n += 2 + l + sovClientTrans(uint64(l))
	}
	if m.MsgInfoJ != nil {
		l = len(m.MsgInfoJ)
		n += 2 + l + sovClientTrans(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovClientTrans(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClientTrans(x uint64) (n int) {
	return sovClientTrans(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Xextend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClientTrans
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Xextend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Xextend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrvId", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SrvId = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TableId = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extend1", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Extend1 = &v
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extend2", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Extend2 = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrvName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.SrvName = &s
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtPayLoad", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtPayLoad = append(m.ExtPayLoad[:0], dAtA[iNdEx:postIndex]...)
			if m.ExtPayLoad == nil {
				m.ExtPayLoad = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClientTrans(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClientTrans
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Xcodec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClientTrans
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Xcodec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Xcodec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoK", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoK = append(m.MsgInfoK[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoK == nil {
				m.MsgInfoK = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Version = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoA", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoA = append(m.MsgInfoA[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoA == nil {
				m.MsgInfoA = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Seq = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoB", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoB = append(m.MsgInfoB[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoB == nil {
				m.MsgInfoB = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SvnName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.SvnName = &s
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoC", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoC = append(m.MsgInfoC[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoC == nil {
				m.MsgInfoC = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FuncName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.FuncName = &s
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoD", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoD = append(m.MsgInfoD[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoD == nil {
				m.MsgInfoD = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Code = &v
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoE", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoE = append(m.MsgInfoE[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoE == nil {
				m.MsgInfoE = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Cmd = &v
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoF", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoF = append(m.MsgInfoF[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoF == nil {
				m.MsgInfoF = []byte{}
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = append(m.Token[:0], dAtA[iNdEx:postIndex]...)
			if m.Token == nil {
				m.Token = []byte{}
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoG", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoG = append(m.MsgInfoG[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoG == nil {
				m.MsgInfoG = []byte{}
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayLoad", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayLoad = append(m.PayLoad[:0], dAtA[iNdEx:postIndex]...)
			if m.PayLoad == nil {
				m.PayLoad = []byte{}
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoH", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoH = append(m.MsgInfoH[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoH == nil {
				m.MsgInfoH = []byte{}
			}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cookies", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cookies = append(m.Cookies[:0], dAtA[iNdEx:postIndex]...)
			if m.Cookies == nil {
				m.Cookies = []byte{}
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoI", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoI = append(m.MsgInfoI[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoI == nil {
				m.MsgInfoI = []byte{}
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendBytes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtendBytes = append(m.ExtendBytes[:0], dAtA[iNdEx:postIndex]...)
			if m.ExtendBytes == nil {
				m.ExtendBytes = []byte{}
			}
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgInfoJ", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClientTrans
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClientTrans
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgInfoJ = append(m.MsgInfoJ[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgInfoJ == nil {
				m.MsgInfoJ = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClientTrans(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClientTrans
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClientTrans(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClientTrans
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClientTrans
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClientTrans
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClientTrans
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClientTrans
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClientTrans        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClientTrans          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClientTrans = fmt.Errorf("proto: unexpected end of group")
)
